export { default as setHeadlessWhen } from './hooks/setHeadlessWhen.js'
export { default as setHeadedWhen } from './hooks/setHeadedWhen.js'
export { default as setSharedCookies } from './hooks/setSharedCookies.js'
export { default as setWindowSize } from './hooks/setWindowSize.js'
export { default as setBrowser } from './hooks/setBrowser.js'
export { default as setBrowserConfig } from './hooks/setBrowserConfig.js'
export { default as setTestHost } from './hooks/setTestHost.js'
export { default as setCommonPlugins } from './hooks/setCommonPlugins.js'
